### ISSUE TITLE
Delete undo button / confirmation

### ISSUE THREAD

**Issue by hubdotcom** [Runbook/runbook#383]
Either provide an undo functionality after the delete occurs (preferred) or confirm that they wish to delete - it's close to the edit button so it's easy to misclick

**Comment by madflojo** [comment]
You know, we actually had this but it looks like it was removed with a redesign. Should be easy enough to re-add it.

https://github.com/Runbook/runbook/blob/02242015/src/web/templates/member/screen-o-death.html#L148
